### ISSUE TITLE
new error re rawsource, with py 3.9 and sphinx 5.3

### ISSUE THREAD

**Issue by ahbarnett** [matthew-brett/texext#12]
Dear Matthew,
I have been enjoying texext with sphinx for years. After some upgrade I now have an error:

```
Exception occurred:
  File "/home/alex/miniconda3/lib/python3.9/site-packages/texext/math_dollar.py", line 176, in _process_node
    in_str = node.rawsource
AttributeError: 'Text' object has no attribute 'rawsource'
```
Here's traceback:
[sphinx-err-9__yna4x.log](https://github.com/matthew-brett/texext/files/9953410/sphinx-err-9__yna4x.log)

Thanks! Alex

**Comment by matthew-brett** [comment]
Just  checking - do you have the latest version of `texext` (0.6.7).  It looks like I thought I had fixed that ...

**Comment by ahbarnett** [comment]
Hi Matthew, sorry, no I pulled via conda install:
texext                    0.6.6                    pypi_0    pypi
Maybe you can update pypi? Thanks for a new tool. Best, Alex
