### ISSUE TITLE
Display math mode with `$$ ... $$`?

### ISSUE THREAD

**Issue by eickenberg** [matthew-brett/texext#8]
Is display mode math (as opposed to inline math) possible by enclosing the math in `$$` on both sides? (If yes, then it should generate a `.. math::` instead of a `:math:` which it doesn't seem to do in my case -- it just shows the $$ on either side and the latex as text)

**Comment by matthew-brett** [comment]
Yes, sure.  I never got round to that because using the `.. math::` directive wasn't much less trouble than the enclosing `$$` markers - but it would be easy to do.

**Comment by eickenberg** [comment]
Right, yes, that makes sense and is what I experienced, since I had the formula on a separate line anyway. Just wanted to know whether this was expected behaviour.

Thanks!
